version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file output.yml
artifacts:
  type: zip
  files:
    - template.yml
    - output.yml
